# Generated by Django 6.0.2 on 2026-02-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='retail.product', verbose_name='Продукты'),
        ),
    ]
