# Generated by Django 6.0.2 on 2026-02-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail',
            name='products',
            field=models.ManyToManyField(blank=True, to='retail.product', verbose_name='Продукты'),
        ),
    ]
